version: '3.7'

services:
  # DB
  vmn-db:
    image: postgres:14-alpine
    container_name: vmn-db
    volumes:
      - vmn-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=vmn
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  # server
  vmn-server:
    build: ./
    container_name: vmn-server
    environment:
      - DB_SERVER=vmn-db
      - POSTGRES_DB=vmn
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 8080:8080
    depends_on:
      - vmn-db

volumes:
  vmn-db-data: