version: '3.7'

services:
  # DB

  # server
  vmn-server:
    build: ./
    image: vmn-server-image
    container_name: vmn-server
    environment:
      - DB_SERVER=vmn-db
      - POSTGRES_DB=vmn
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PORT=8080
      - JWT_KEY=PyVjynySBpFOs2uSpoON6ge4DV/U+QmBpA7LGh0aQvfoceQbruI6gCQaUxJL5f6w
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PASSWORD=avxa vvxm emcs uklq
      - MAIL_USERNAME=vmn@gitam.edu
      - DATABASE_CONNECTION_URL=jdbc:postgresql://ep-gentle-cake-a1a28msa.ap-southeast-1.aws.neon.tech/VMN?sslmode=require
      - DATABASE_PASSWORD=Hy5TDhMnJtl9
      - DATABASE_USERNAME=VMN_owner
    ports:
      - 8080:8080


